# version: "3.9"
services:
  postgres_auth:
    image: postgres:14.8-alpine3.18
    container_name: postgres_auth
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGSSLMODE: "disable"
    # env_file: -- сделать когда-нибудь
    #   - ./services/gateway/.env
    volumes:
      - ./services/auth/migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  auth:
    image: auth
    build:
      context: ./services/auth
      dockerfile: dev.Dockerfile
    container_name: auth
    ports:
      - "8080:8080"
    # env_file:
    #   - ./services/gateway/.env
    volumes:
      - ./services/auth:/usr/src/app
    depends_on:
      - postgres_auth

