#конфигурация сервиса

env: "local" #or dev or prod
token_ttl: "1h"

grpc:
  port: "8080"
  host: "localhost"
  timaout: "1h"

db:
  username: "postgres"
  password: "qwerty"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"
