#конфигурация сервиса

#env: "local" #or dev or prod

login:
  token_ttl: "1h"

grpc:
  port: "8080"
  host: "host.docker.internal"
  timaout: "1h"
  env: "local"

db:
  username: "postgres"
  password: "qwerty"
  host: "host.docker.internal"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
