env: "local"



grpc:
  port: "8001"
  host: "localhost"
  timaout: "1h"
  token_ttl: "1h"

db:
  username: "postgres"
  password: "qwerty"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

